// NODE_PATH=<work>/resource-tests/node_modules node --test tests/resource-catalog-v2-sql.test.cjs
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');
const migration = fs.readFileSync(path.join(__dirname, '../database/20260927-public-resource-catalog-v2.sql'), 'utf8');
const v1 = fs.readFileSync(path.join(__dirname, '../database/20260927-public-resource-catalog.sql'), 'utf8');
async function setup() {
    const db = new PGlite();
    await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE unrelated_role;
      CREATE TABLE public.videos(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,course text,day_number integer,video_number integer,resources jsonb,description text);
      ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;`);
    await db.exec(v1);
    return db;
}
async function insert(db, course, day, video, resources) {
    return (await db.query('INSERT INTO public.videos(course,day_number,video_number,resources,description) VALUES($1,$2,$3,$4::jsonb,$5) RETURNING id', [course,day,video,JSON.stringify(resources),'SECRET_LESSON_TEXT'])).rows[0].id;
}
const resource = (title, group, overrides={}) => ({title,group,url:'https://private.example/PRIVATE_LINK',description:'SECRET_RESOURCE_TEXT',...overrides});

test('v2 preserves real days, source group order and normalized ordinals without changing v1', async () => {
    const db = await setup();
    try {
        // Deliberately insert sessions out of sequence and templates out of numeric order.
        await insert(db, 'industrial-training-mastery', 2, 20, [
            resource('Industrial CV Template 10',' CV Templates '),
            resource('Industrial CV Template 2','cv templates'),
            resource('Cover Letter Template 1','Cover Letter Templates'),
            resource('Industrial CV Template 1','CV Templates'),
            resource('Draft with sentinels','CV Templates',{url:' undefined ',view_storage_path:'None',download_storage_path:' NULL '}),
            resource('Hidden resource','CV Templates',{catalog_hidden:true}),
            resource('   ','CV Templates'),
            resource({private:'PRIVATE_NESTED_TITLE'},'CV Templates')
        ]);
        await insert(db, 'industrial-training-mastery', 2, 3, [
            resource('Industrial CV Template 2','CV Templates',{catalog_priority:7}),
            resource('Interview guide',''),
            resource('Cover Letter Template 2','Cover Letter Templates')
        ]);
        await insert(db, 'industrial-training-mastery', 10, 101, [resource('Industrial CV Template 2','CV Templates')]);
        await insert(db, 'industrial-training-mastery', 0, 901, JSON.stringify([resource('Welcome checklist','General Resources')]));
        await insert(db, 'industrial-training-mastery', null, 17, [resource('Undated guide',{private:'PRIVATE_NESTED_GROUP'})]);
        await insert(db, 'industrial-training-mastery', 2, 999, 'malformed JSON');
        await insert(db, 'msc-ca-freshers-program', 1, 7, [resource('Industrial CV Template 2','CV Templates')]);
        await insert(db, 'msc-articleship-program', 1, 5, [resource('Articleship CV Template 1',' CV Templates ')]);
        await insert(db, 'other-program', 1, 1, [resource('Unrelated','Other')]);
        const before = await db.query("SELECT pg_get_functiondef('public.get_public_resource_catalog(text)'::regprocedure) AS definition");
        await db.exec(migration);
        await db.exec(migration); // Idempotent; no source data changes or v1 replacement.
        const after = await db.query("SELECT pg_get_functiondef('public.get_public_resource_catalog(text)'::regprocedure) AS definition");
        assert.equal(after.rows[0].definition,before.rows[0].definition);
        assert.equal((await db.query('SELECT count(*)::int AS count FROM public.videos')).rows[0].count,9);
        await db.exec('SET ROLE anon');
        const rows=(await db.query("SELECT * FROM public.get_public_resource_catalog_v2('industrial-training')")).rows;
        assert.equal(rows.length,9);
        assert.deepEqual(rows.map(row=>row.day_number),[0,2,2,2,2,2,2,10,null]);
        const day2=rows.filter(row=>row.day_number===2);
        assert.deepEqual([...new Set(day2.map(row=>row.group_name))],['CV Templates','General Resources','Cover Letter Templates']);
        const cv=day2.filter(row=>row.group_name==='CV Templates');
        assert.deepEqual(cv.map(row=>row.title),['Industrial CV Template 2','Industrial CV Template 10','Industrial CV Template 1']);
        assert.deepEqual(cv.map(row=>row.resource_order),[1,2,3]);
        assert.deepEqual(cv.map(row=>row.session_order),[1,2,2]);
        assert.deepEqual(cv.map(row=>row.group_order),[1,1,1]);
        assert.equal(cv[0].sort_order,7,'the duplicate retains its earliest placement and priority');
        assert.equal(day2.find(row=>row.title==='Interview guide').group_order,2);
        assert.equal(day2.find(row=>row.title==='Cover Letter Template 2').group_order,3);
        const repeated=rows.filter(row=>row.title==='Industrial CV Template 2');
        assert.equal(repeated.length,2,'a repeated title on a different day remains available');
        assert.notEqual(repeated[0].resource_key,repeated[1].resource_key);
        assert.equal(rows.at(-1).group_name,'General Resources','a malformed group object is not stringified');
        const all=(await db.query('SELECT * FROM public.get_public_resource_catalog_v2()')).rows;
        assert.equal(all.length,11);
        assert.equal(all.filter(row=>row.program_type==='articleship').length,1);
        assert.equal((await db.query("SELECT * FROM public.get_public_resource_catalog_v2('unknown')")).rows.length,0);
    } finally {await db.close();}
});

test('v2 exposes only safe names/grouping fields to anon and authenticated callers', async () => {
    const db=await setup();
    try {
        await insert(db,'msc-ca-freshers-program',3,8675309,[resource('CV Guide',' CV Templates ',{view_storage_path:'PRIVATE_STORAGE',download_storage_path:'PRIVATE_DOWNLOAD',type:'pdf',catalog_category:'cv-prep',catalog_priority:4})]);
        await db.exec(migration);
        const expected=['resource_key','program_type','title','category','sort_order','day_number','group_name','session_order','group_order','resource_order'].sort();
        for (const role of ['anon','authenticated']) {
            await db.exec('SET ROLE '+role);
            const rows=(await db.query("SELECT * FROM public.get_public_resource_catalog_v2('ca-fresher')")).rows;
            assert.equal(rows.length,1);
            assert.deepEqual(Object.keys(rows[0]).sort(),expected);
            assert.equal(rows[0].session_order,1);
            assert.equal(rows[0].group_name,'CV Templates');
            assert.ok(!/PRIVATE|SECRET|https:|8675309/.test(JSON.stringify(rows)));
            await assert.rejects(db.query('SELECT resources FROM public.videos'),/permission denied/);
            await assert.rejects(db.query("SELECT public.msc_resource_array('[]'::jsonb)"),/permission denied/);
            await db.exec('RESET ROLE');
        }
        await db.exec('SET ROLE unrelated_role');
        await assert.rejects(db.query('SELECT * FROM public.get_public_resource_catalog_v2()'),/permission denied/);
    } finally {await db.close();}
});

test('v2 reflects source insert, update and deletion automatically with no invented day assignments', async () => {
    const db=await setup();
    try {
        await db.exec(migration);
        await db.exec('SET ROLE anon');
        assert.equal((await db.query("SELECT * FROM public.get_public_resource_catalog_v2('articleship')")).rows.length,0);
        await db.exec('RESET ROLE');
        const id=await insert(db,'msc-articleship-program',null,42,[resource('Initial guide','')]);
        await db.exec('SET ROLE anon');
        const initial=(await db.query("SELECT * FROM public.get_public_resource_catalog_v2('articleship')")).rows;
        assert.equal(initial[0].day_number,null);
        assert.equal(initial[0].group_name,'General Resources');
        await db.exec('RESET ROLE');
        await db.query('UPDATE public.videos SET day_number=3,resources=$1::jsonb WHERE id=$2',[JSON.stringify([resource('CV Template 2','CV Templates'),resource('CV Template 10','CV Templates')]),id]);
        await db.exec('SET ROLE anon');
        const updated=(await db.query("SELECT * FROM public.get_public_resource_catalog_v2('articleship')")).rows;
        assert.deepEqual(updated.map(row=>row.title),['CV Template 2','CV Template 10']);
        assert.ok(updated.every(row=>row.day_number===3&&row.group_name==='CV Templates'));
        assert.deepEqual(updated.map(row=>row.resource_order),[1,2]);
        await db.exec('RESET ROLE');
        await db.query('DELETE FROM public.videos WHERE id=$1',[id]);
        await db.exec('SET ROLE anon');
        assert.equal((await db.query("SELECT * FROM public.get_public_resource_catalog_v2('articleship')")).rows.length,0);
    } finally {await db.close();}
});
