backend:
  name: git-gateway

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter" 
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", optional: true }
      - label: "Full HTML Content"
        name: "body"
        widget: "code"
        hint: "Enter blog code, preferably inside the content."
        options:
          language: "html"
          allow_language_selection: false
        default: |
          <!DOCTYPE html>
          <html lang="en" class="scroll-smooth">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{{title}}</title>
            <meta name="description" content="Blog post: {{title}}">
            <link rel="icon" type="image/x-icon" href="/assets/icon-70x70.png">
            <script src="https://cdn.tailwindcss.com"></script>
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@700&family=Merriweather:wght@400;700&display=swap" rel="stylesheet">
            <style>
              body {
                font-family: 'Inter', sans-serif;
                background-color: #f8fafc;
                color: #334155;
                line-height: 1.7;
              }
              .blog-container {
                max-width: 850px;
                margin: 0 auto;
                background-color: white;
                box-shadow: 0 15px 35px rgba(0,0,0,0.08);
                border-radius: 20px;
                overflow: hidden;
              }
              .blog-header {
                background: linear-gradient(135deg, #4f46e5 0%, #3b82f6 100%);
                color: white;
                padding: 3.5rem 2.5rem;
                text-align: center;
                position: relative;
                overflow: hidden;
              }
              .blog-header::before {
                content: '';
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                background: url("data:image/svg+xml,%3Csvg width='100' height='100' viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M11 18c3.866 0 7-3.134 7-7s-3.134-7-7-7-7 3.134-7 7 3.134 7 7 7zm48 25c3.866 0 7-3.134 7-7s-3.134-7-7-7-7 3.134-7 7 3.134 7 7 7zm-43-7c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zm63 31c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zM34 90c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zm56-76c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zM12 86c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm28-65c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm23-11c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zm-6 60c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm29 22c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zM32 63c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zm57-13c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zm-9-21c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zM60 91c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zM35 41c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zM12 60c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2z' fill='%23ffffff' fill-opacity='0.08' fill-rule='evenodd'/%3E%3C/svg%3E");
                opacity: 0.6;
              }
              .blog-title {
                font-family: 'Playfair Display', serif;
                font-size: 2.8rem;
                margin-bottom: 1rem;
                color: white;
                position: relative;
                text-shadow: 0 2px 4px rgba(0,0,0,0.1);
              }
              .blog-meta {
                opacity: 0.9;
                font-size: 1rem;
                font-weight: 500;
                letter-spacing: 0.5px;
                position: relative;
              }
              .floating-header {
                background-color: rgba(255,255,255,0.95);
                backdrop-filter: blur(10px);
                box-shadow: 0 4px 12px rgba(0,0,0,0.08);
                border-bottom: 1px solid rgba(0,0,0,0.05);
                transition: all 0.3s ease;
              }
              .footer-nav {
                background-color: white;
                box-shadow: 0 -4px 12px rgba(0,0,0,0.05);
                border-top: 1px solid rgba(0,0,0,0.05);
              }
              .footer-tab {
                transition: all 0.3s ease;
                position: relative;
              }
              .footer-tab::after {
                content: '';
                position: absolute;
                bottom: -3px;
                left: 50%;
                width: 0;
                height: 2px;
                background: #3b82f6;
                transition: all 0.3s ease;
                transform: translateX(-50%);
              }
              .footer-tab:hover {
                color: #3b82f6;
                transform: translateY(-3px);
              }
              .footer-tab:hover::after {
                width: 70%;
              }
              .whatsapp-button {
                background-color: #25D366;
                color: white;
                border-radius: 50px;
                padding: 14px 22px;
                box-shadow: 0 6px 18px rgba(37,211,102,0.35);
                transition: all 0.3s ease;
                border: none;
                outline: none;
              }
              .whatsapp-button:hover {
                transform: translateY(-5px) scale(1.03);
                box-shadow: 0 8px 25px rgba(37,211,102,0.45);
              }
              .brand-link {
                transition: transform 0.3s ease;
              }
              .brand-link:hover {
                transform: scale(1.05);
              }
              .auth-buttons svg {
                transition: transform 0.3s ease;
              }
              .auth-buttons svg:hover {
                transform: scale(1.15);
                color: #4f46e5;
              }
              article {
                font-family: 'Merriweather', serif;
              }
              article p {
                font-size: 1.05rem;
                color: #475569;
                margin-bottom: 1.5rem;
              }
              .reading-progress-container {
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 4px;
                background: transparent;
                z-index: 1000;
              }
              .reading-progress-bar {
                height: 100%;
                background: linear-gradient(90deg, #4f46e5, #3b82f6);
                width: 0%;
                transition: width 0.2s ease;
              }
              .content-decoration::before {
                content: '';
                position: absolute;
                top: -15px;
                left: -15px;
                width: 30px;
                height: 30px;
                border-top: 3px solid #3b82f6;
                border-left: 3px solid #3b82f6;
              }
              .content-decoration::after {
                content: '';
                position: absolute;
                bottom: -15px;
                right: -15px;
                width: 30px;
                height: 30px;
                border-bottom: 3px solid #3b82f6;
                border-right: 3px solid #3b82f6;
              }
              .copied-tooltip {
                opacity: 0;
                transition: opacity 0.3s ease;
              }
            </style>
          </head>
          <body class="bg-gray-50">
            <div class="reading-progress-container">
              <div class="reading-progress-bar" id="reading-progress"></div>
            </div>

            <div class="floating-header fixed top-0 left-0 right-0 z-50">
              <div class="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
                <a href="/" class="brand-link flex items-center space-x-3">
                  <img src="https://mystudentclub.pages.dev/assets/logo.png" alt="My Student Club" class="h-10 w-auto">
                </a>
                <div class="flex items-center space-x-6">
                  <a href="#" class="hidden md:block text-slate-600 hover:text-blue-600 transition-colors text-sm font-medium">Home</a>
                  <a href="/login.html" class="text-slate-600 hover:text-blue-600 transition-colors">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                  </a>
                </div>
              </div>
            </div>

            <main class="container mx-auto px-4 pt-28 pb-24">
              <div class="blog-container rounded-2xl overflow-hidden shadow-xl">
                <div class="blog-header">
                  <h1 class="blog-title">{{title}}</h1>
                  <p class="blog-meta flex items-center justify-center space-x-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2 opacity-90" viewBox="0 0 20 20" fill="currentColor">
                      <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
                    </svg>
                    <span>Published on: {{date | date('MMMM D, YYYY')}}</span>
                  </p>
                </div>
                
                <article class="p-8 md:p-12 bg-white relative">
                  <div class="content-decoration relative mb-8">
                    <div class="flex items-center mb-6 text-sm text-slate-500">
                      <span class="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-xs font-semibold mr-3">Educational</span>
                      <span class="flex items-center mr-4">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        5 min read
                      </span>
                    </div>
                    
                    <p class="text-slate-700 leading-relaxed">Start writing your blog post content here...</p>
                  </div>
                  
                  <div class="mt-10 pt-8 border-t border-slate-100">
                    <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                      <div class="flex items-center space-x-3">
                        <img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='50' height='50'%3E%3Ccircle cx='12' cy='12' r='12' fill='%234f46e5' opacity='0.2'/%3E%3Ccircle cx='12' cy='9' r='3' fill='%234f46e5'/%3E%3Cpath d='M12 12c-2.761 0-5 2.239-5 5v1h10v-1c0-2.761-2.239-5-5-5z' fill='%234f46e5'/%3E%3C/svg%3E" alt="Author" class="w-12 h-12 rounded-full">
                        <div>
                          <p class="font-semibold text-slate-800">Written by</p>
                          <p class="text-sm text-slate-600">Admin</p>
                        </div>
                      </div>
                      
                      <div class="flex space-x-2 relative">
                        <button id="shareButton" class="px-4 py-2 border border-slate-200 rounded-lg text-slate-600 hover:bg-slate-50 transition-colors text-sm font-medium flex items-center">
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
                          </svg>
                          Share
                        </button>
                        <span id="copiedTooltip" class="absolute -top-8 left-1/2 transform -translate-x-1/2 bg-slate-800 text-white text-xs px-2 py-1 rounded copied-tooltip">Copied!</span>
                      </div>
                    </div>
                  </div>
                </article>
              </div>

              
            </main>

            <a href="https://api.whatsapp.com/send/?phone=919313148303" target="_blank" class="whatsapp-button fixed bottom-24 right-5 z-50 flex items-center space-x-2 text-sm font-medium">
              <svg class="w-5 h-5" viewBox="0 0 24 24" fill="currentColor">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M20.463 3.488C18.217 1.24 15.231 0 12.05 0 5.495 0 0.165 5.33 0.157 11.885c0 2.096.548 4.139 1.595 5.942L0 24l6.335-1.661a11.88 11.88 0 5.683 1.458c6.548 0 11.877-5.33 11.882-11.885.008-3.173-1.231-6.161-3.487-8.422zm-8.413 18.26h-.004a9.88 9.88 0 01-5.042-1.382l-.36-.215-3.735.978.998-3.648-.236-.374a9.883 9.883 0 01-1.518-5.221c.005-5.467 4.458-9.92 9.93-9.92 2.65.004 5.142 1.032 7.018 2.908 1.872 1.88 2.902 4.374 2.9 7.026-.008 5.467-4.457 9.92-9.931 9.92zm5.43-7.424c-.299-.149-1.772-.875-2.048-.974-.277-.099-.478-.148-.678.149-.2.298-.774.975-.95 1.174-.173.199-.347.224-.647.075-.3-.15-1.263-.465-2.408-1.483-.89-.795-1.49-1.777-1.663-2.076-.174-.298-.018-.46.13-.608.135-.133.3-.349.45-.522.15-.174.2-.298.3-.497.099-.199.05-.374-.026-.524-.075-.149-.677-1.631-.927-2.233-.244-.584-.492-.505-.676-.513-.173-.010-.374-.010-.574-.010-.2 0-.523.075-.797.374-.273.298-1.047.974-1.047 2.38 0 1.406 1.022 2.763 1.172 2.962.15.199 2.15 3.284 5.164 4.6.55.24 1.173.5 1.574.639.661.21 1.262.18 1.736.11.53-.08 1.633-.668 1.863-1.314.23-.645.23-1.2.16-1.315-.075-.15-.274-.238-.574-.397z"/>
              </svg>
              <span>Contact Us</span>
            </a>

            <script>
              window.addEventListener('scroll', function() {
                const winScroll = document.body.scrollTop || document.documentElement.scrollTop;
                const height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
                const scrolled = (winScroll / height) * 100;
                document.getElementById("reading-progress").style.width = scrolled + "%";
              });
              
              window.addEventListener('scroll', function() {
                const header = document.querySelector('.floating-header');
                if (window.scrollY > 10) {
                  header.classList.add('shadow-md');
                } else {
                  header.classList.remove('shadow-md');
                }
              });

              document.getElementById('shareButton').addEventListener('click', function() {
                const currentUrl = window.location.href;
                
                const tempTextArea = document.createElement('textarea');
                tempTextArea.value = currentUrl;
                document.body.appendChild(tempTextArea);
                
                tempTextArea.select();
                document.execCommand('copy');
                
                document.body.removeChild(tempTextArea);
                
                const tooltip = document.getElementById('copiedTooltip');
                tooltip.style.opacity = '1';
                
                setTimeout(() => {
                  tooltip.style.opacity = '0';
                }, 2000);
              });
            </script>
          </body>
          </html>