backend:
  name: git-gateway

media_folder: "assets" # Keep if you need uploads

collections:
  - name: "test"
    label: "Test"
    folder: "test_posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }